# Contains lists of values to pull random player data from.

firstNames = ["Michael", "Henri", "Ethan", "Gerrit", "Jake", "Baby", "Bob", "Gary", "Gregory", "Luis-Scott", "Ian", "Evan", "Steve", "Jonathan", "John", "Connor", "Paul", "Timothy", "Simon", "Peter", "David", "Abraham", "Joseph", "Jay", "Raymond", "Nate", "Allan", "Ivan", "William", "Austin", "Eric", "Caleb", "Anthony", "Jeoff", "Nick", "Samuel", "Sam", "Sammy", "Elijah", "Ben", "Jeremy", "Jeremiah", "Joel", "Chris", "Tyler", "Philip", "Phil", "Mark", "Luke", "Matthew", "Saun", "Tucker", "Luis", "Felix", "Ryan", "Shane", "Seth", "Brandon", "Bo", "Alex", "Alexander", "Julius", "TJ", "AJ", "Mark-David", "John-Paul", "Benowitz", "Hassan", "JJ", "Rob", "Jackie", "Jonah", "Amos", "Hunter", "Mick", "Madison", "Aaron", "Scottie", "Kris", "Kole", "Robin", "Max", "Matt", "Adam", "Cooper", "Nelson", "Charlie", "Charles", "Freddy", "Richard", "Donald", "HP", "Walter", "Jack", "Marvin", "Davis", "Roger", "Herbert", "Stevie", "Jose", "Ozzie", "Darryl", "Nomar", "Stan", "Stanley", "Mario", "Luigi", "Francisco", "Frank", "Chip", "Rick", "Pierre", "Mickey", "Hank", "Barry", "Sandy", "Patrick", "Patty", "Benjamin", "Boots", "Pretzel", "Mordecai", "Cain", "Abel", "Dizzy", "Hugh", "Snuffy", "Buttercup", "Bombo", "Bud", "Graham", "Razor", "Dick", "Dickie", "Hawkins", "Nolan", "Dolan", "Quinton", "Julian", "Manny", "Tony", "Julio", "Roberto", "Albert", "Alberto", "Rod", "Edgar", "Miguel", "Omar", "Rafael", "Donatello", "Michelangelo", "Leonardo", "Rex", "Carter", "Quinn", "Kazuo", "Akinori", "Kenji", "Kazuhiro", "Tadahito", "Tomo", "Nori", "Hideki", "Wei-Yin", "Takashi", "Chan-Ho", "Koji", "Ichiro", "Hideki", "Larry", "Ronald", "Ol’", "Marcus", "George", "Georgie", "Georgio", "Juan", "Cedric", "Randy", "Salvador", "Jason", "Dexter", "Tom", "Christian", "Dominic", "Lewis", "John-Lewis", "Eddie", "Edison", "Ed", "Elvis", "Titus", "Glenn", "Amed", "Francis", "Thomas", "Tommy", "Clark", "Muhammad"]

lastNames = ["Orange", "Cruz", "Curry", "Robinson", "Vargas", "Widstrom", "Diaz", "Dunn", "Storm", "Green", "Fish", "Clock", "McDonald", "Fairbanks", "Baker", "Wheeler", "Steelcraft", "Finnegan", "Fox", "Foster", "Freeland", "Fry", "Fuller", "Mullin", "Carver", "Garcia", "Gonzalez", "Honeycutt", "Barber", "Smith", "Tanner", "Shoemaker", "Hatch", "Hendrix", "Hill", "Brock", "Holloway", "Football", "Kelley", "Knight", "Lewis", "Long", "Lynch", "Martin", "McCarthy", "Meyers", "Moore", "Murphy", "O'Brian", "Park", "Peacock", "Ramos", "Jellico", "Romero", "Rupert", "Santos", "Scott", "Sears", "Shepherd", "Hancock", "Buxton", "Winefire", "McBride", "McKnight", "Sugar", "Graves", "Parks", "Casey", "Austin", "Bruce", "Duffy", "Stanton", "Seager", "Short", "Singer", "Small", "Solomon", "Taylor", "Torres", "Walton", "Wilson", "Diamonds", "Box", "Gray", "Glover", "Benson", "Kennedy", "Langley", "Lopez", "Dawson", "October", "Sweets", "Anderson", "Thomas", "Wright", "Ward", "Wood", "Fisher", "Mason", "Brown", "Strawberry", "Sosa", "Star", "Bolt", "DiMaggio", "Rivera", "Young", "Trout", "Blackbird", "Legg", "Grant", "High", "Bonsor", "Clap", "Graham", "Pole", "Hawks", "McCracker", "Boyd", "Havoc", "Thunder", "Thundercock", "Church", "Archer", "Hicks", "Tall", "Badoo", "Bard", "Scoop" "Trammel", "Parker", "Presley", "Frog", "Rosario", "Rhinehart", "McMan", "Ball", "Smithson", "Clay", "Red", "Castro", "Robles", "Arcia", "Mercury", "Atlas", "Winter", "Buxton", "Bell", "Roberts", "Banks", "Rivers", "Mays", "Spring", "Oak", "Irving", "Foote", "Hoffman", "Freidman", "Australia", "Berstein", "Plates", "Bing", "Pole", "Jones", "Brown", "Williams", "Hall", "Ahir", "Lane", "Spears", "Larson", "Lawson", "Lang", "Snyder", "Simpson", "Stone", "Willcox", "Willy", "Creek", "Strange", "Doby", "Sacks", "Sauce", "Kicks", "Wakely", "Vanwright", "Wiemer", "Jordan", "Justice", "Judd", "Griffin", "Foreman", "Timber", "Grossman", "Peterson", "Price", "Pride", "Page", "Freeman", "Fletcher", "Barq"]

ethnicities = ["White", "White", "White", "White", "Hispanic", "Hispanic", "Asian", "Black", "Black"]

quirks = ["", "All-Star", "One-Eyed", "Fast Fingers", "Fan Favorite", "Womanizer", "Fastball Specialist", "Curveball Specialist", "Slugger", "Cool-Headed", "Cheater", "Dugout Comedian", "War Veteran", "Speed Freak", "Egomaniac", "Coach’s Son", "Child Prodigy", "King of the Jungle", "Laidback", "Trickster", "At-Bat Taunter", "Base Thief", "Glass Bones", "Killjoy", "Sprinter", "Giant", "Old-Fashioned", "Honorable", "Loose-Lipped", "Rules Lawyer"]

battingStyles = ["Go For Broke", "Cautious", "Crowd Pleaser", "Gwynn", "Carew", "Great Bambino", "Overthinker", "Blank-Slate", "Book Worm", "Bunt-Heavy", "Foul-Mouthed", "Executor", "Etcha-Sketch", "Bane of Pitchers", "Water Boy", "Improvised", "Hungover", "Self Sacrifice", "Arm of God", "Roulette Wheel"]

pitchingStyles = ["Knucklehead", "Kershaw", "Fork", "Fastball-Heavy", "Curveball-Heavy", "Ump-Hugger", "Paranoid", "Spoon", "Magician", "Caveman", "Blank-Slate", "Overthinker", "Base-Checker", "Crowd Pleaser", "Matthewson", "Splitterball-Heavy", "Bowler", "Hands of God", "Bruiser", "Roulette Wheel"]